export enum MutationType {
    SET_OPEN_KEYS = 'SET_OPEN_KEYS',
    SET_SELECTED_KEYS = 'SET_SELECTED_KEYS',
    ADD_TAB_LIST = 'ADD_TAB_LIST',
    REMOVE_TAB_LIST = 'REMOVE_TAB_LIST',
    RESET_TAB_LIST = 'RESET_TAB_LIST'
}
